# Generated by Django 2.2 on 2019-02-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('realname', models.CharField(max_length=300)),
                ('accountnumber', models.CharField(max_length=300)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=300)),
                ('dog_color', models.CharField(max_length=300)),
                ('dog_breed', models.CharField(max_length=300)),
                ('dog_gender', models.CharField(max_length=300)),
            ],
        ),
    ]
